# base image
FROM node:20-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH ./node_modules/.bin:$PATH

# install and cache app dependencies
# COPY package.json ./
COPY package*.json ./

RUN npm install

# RUN mkdir -p ./node_modules/.cache && chmod -R 777 ./node_modules/.cache

COPY ./ ./

EXPOSE 3000

# RUN chown -R node /app/node_modules
# USER node

# start app
CMD ["npm", "run", "dev"]
