version: '3.7'
services:
  # redis-server:
  #   image: redis
  #   # optional: specifiy 6379 default port
  #   ports:
  #     - "6379"
  client:
    # restart: always
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3001:3000"
    volumes: 
      - /app/node_modules
      - ./client:/app
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "4001:4000"
    volumes:
      - /app/node_modules
      - ./server:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    ports:
      - "5001:5000"
    volumes:
      - /app/node_modules
      - ./worker:/app
