version: '3.7'
services:
  # redis-server:
  #   image: redis
  #   # optional: specifiy 6379 default port
  #   ports:
  #     - "6379"
  client:
    # restart: always
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3001:3000" # Map host port 3001 to container port 3000
    volumes: 
      - /app/node_modules
      - ./client:/app
