# base image
FROM node:18-alpine

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY package.json ./

RUN npm install

# RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY ./ ./

# RUN chown -R node /app/node_modules
# USER node

# start app
CMD ["npm", "run", "start"]
